### ISSUE TITLE
Raspberry Pi 3B+ Support

### ISSUE THREAD

**Issue by vaccinemedia** [amtuannguyen/karaoke420#1]
I've just followed the instructions in the readme as follows:
Used Etcher to write OSMC latest version as of June 2019 to an SD Card
Booted using the sd card
Enabled and got onto wifi
Logged onto the pi using credentials osmc:osmc
Installed git
Cloned the repo in the readme
CD into the karaoke420 folder
Ran ./osmc-setup.sh
It installed some things including bundler and a bunch of gems
Then it appeared to halt with some output (see attached) and running the later commands in the readme also had issues (see other attached)
Would it be possible to upload a youtube video showing what you say in the readme from a clean install back to back? I'm not sure if this works with the latest versions of osmc perhaps and needs further testing> I can see your code is 2 years  old and may need an update?
![Screenshot 2019-07-18 at 01 29 49](https://user-images.githubusercontent.com/10465885/61420889-89490600-a8fc-11e9-90b8-82f29f2eab4a.png)
![Screenshot 2019-07-18 at 01 31 00](https://user-images.githubusercontent.com/10465885/61420892-8b12c980-a8fc-11e9-8742-d284c83fcee2.png)

**Comment by vaccinemedia** [comment]
browsing to osmc.local:3000 gives:
Puma caught this error: Missing `secret_key_base` for 'development' environment, set this value in `config/secrets.yml` (RuntimeError)
/var/lib/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:510:in `validate_secret_key_config!'
/var/lib/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:247:in `env_config'
/var/lib/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:692:in `build_request'
/var/lib/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:518:in `build_request'
/var/lib/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:521:in `call'
/var/lib/gems/2.3.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.3.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
/var/lib/gems/2.3.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
/var/lib/gems/2.3.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
/var/lib/gems/2.3.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
